/** @type {import("tailwindcss").Config} */

export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "text-color-dark": "var(--text-color-dark)",
        "text-color-gray": "var(--text-color-gray)",
        "text-color-gray-light": "var(--text-color-gray-light)",
        "border-color-gray": "var(--border-color-gray)",
        "color-navy": "var(--color-navy)",
        "color-blue": "var(--color-blue)",
        "color-blue-hover": "var(--color-blue-hover)",
        "color-blue-light": "var(--color-blue-light)",
        "color-green": "var(--color-green)",
        "color-green-10": "var(--color-green-10)",
        "color-green-70": "var(--color-green-70)",
        "color-red": "var(--color-red)",
        "color-red-10": "var(--color-red-10)",
        "color-red-70": "var(--color-red-70)",
        "color-orange": "var(--color-orange)",
        "color-orange-10": "var(--color-orange-10)",
        "color-orange-70": "var(--color-orange-70)",
        "color-white": "var(--color-white)",
        "color-black-5": "var(--color-black-5)",
        "color-black-10": "var(--color-black-10)",
        "color-black-50": "var(--color-black-50)",
      },
      width: {
        "modal-default-width": "640px",
      },
      height: {
        "container-height": "calc(100% - 100px)",
        "modal-default-height": "360px",
        "modal-content-height": "calc(100% - 32px)",
      },
      backgroundImage: {
        "not-found": "var(--not-found-image)",
      },
      boxShadow: {
        "t-sm": "var(--box-shadow-t-sm)",
        "t-md": "var(--box-shadow-t-md)",
        "t-lg": "var(--box-shadow-t-lg)",
        "t-xl": "var(--box-shadow-t-xl)",
        "t-2xl": "var(--box-shadow-t-2xl)",
        "t-3xl": "var(--box-shadow-t-3xl)",
        "b-sm": "var(--box-shadow-b-sm)",
        "b-md": "var(--box-shadow-b-md)",
        "b-lg": "var(--box-shadow-b-lg)",
        "b-xl": "var(--box-shadow-b-xl)",
        "b-2xl": "var(--box-shadow-b-2xl)",
        "b-3xl": "var(--box-shadow-b-3xl)",
        "l-sm": "var(--box-shadow-l-sm)",
        "l-md": "var(--box-shadow-l-md)",
        "l-lg": "var(--box-shadow-l-lg)",
        "l-xl": "var(--box-shadow-l-xl)",
        "l-2xl": "var(--box-shadow-l-2xl)",
        "l-3xl": "var(--box-shadow-l-3xl)",
        "r-sm": "var(--box-shadow-r-sm)",
        "r-md": "var(--box-shadow-r-md)",
        "r-lg": "var(--box-shadow-r-lg)",
        "r-xl": "var(--box-shadow-r-xl)",
        "r-2xl": "var(--box-shadow-r-2xl)",
        "r-3xl": "var(--box-shadow-r-3xl)",
      },
    },
  },
  plugins: [],
};
